In [2]:
# Import libraries
import os,cv2
import numpy as np
import matplotlib.pyplot as plt

from sklearn.utils import shuffle
from sklearn.cross_validation import train_test_split

from keras import backend as K
K.set_image_dim_ordering('tf')

from keras.utils import np_utils
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation, Flatten
from keras.layers.convolutional import Convolution2D, MaxPooling2D
from keras.optimizers import SGD,RMSprop,adam


In [3]:
PATH = os.getcwd()
# Define data path
data_path = PATH + '/shortdata'
data_dir_list = os.listdir(data_path)

img_rows=224
img_cols=224
num_channel=3
num_epoch=20
num_classes = 2

USE_SKLEARN_PREPROCESSING='True'
if USE_SKLEARN_PREPROCESSING:
    # using sklearn for preprocessing
    from sklearn import preprocessing

    def image_to_feature_vector(image, size=(224, 224)):
        # resize the image to a fixed size, then flatten the image into
        # a list of raw pixel intensities
        return cv2.resize(image, size).flatten()
    img_data_dict={}
    for i in range(10):
        img_data_dict[i]=[]
    j=0
    k=0
    for dataset in data_dir_list:
        data_dir_list2=os.listdir(data_path+'/'+ dataset)
        for dataset1 in data_dir_list2: 
            img_list=os.listdir(data_path+'/'+dataset+'/'+dataset1)
            for img in img_list:
                input_img=cv2.imread(data_path + '/'+ dataset + '/'+dataset1+'/'+ img)
                #path=os.path.join(data_path, dataset, dataset1,img)
                #print(path)
                if input_img is not None:
                    #input_img=cv2.cvtColor(input_img, cv2.COLOR_BGR2GRAY)
                    input_img_flatten=image_to_feature_vector(input_img,(224,224))
                    img_data_dict[j].append(input_img_flatten)    
            j=j+1
    #working on video 0
    img_data = np.array(img_data_dict[1])
    img_data = img_data.astype('float32')
    print (img_data.shape)
    img_data_scaled = preprocessing.scale(img_data)
    print (img_data_scaled.shape)
    
    print (np.mean(img_data_scaled))
    print (np.std(img_data_scaled))

    print (img_data_scaled.mean(axis=0))
    print (img_data_scaled.std(axis=0))
    img_data_scaled=img_data_scaled.reshape(img_data.shape[0],img_rows,img_cols,num_channel)
    print (img_data_scaled.shape)
    


(150, 150528)


/home/ubuntu/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/data.py:164: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "
/home/ubuntu/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/data.py:181: UserWarning: Numerical issues were encountered when scaling the data and might not be solved. The standard deviation of the data is probably very close to 0. 
  warnings.warn("Numerical issues were encountered "


(150, 150528)
-3.7952343e-09
1.0
[-1.0405977e-08  7.9472862e-10  6.3578289e-09 ... -9.5367430e-09
  5.0415596e-09  5.5631002e-09]
[1.0000002  0.99999994 0.9999998  ... 0.99999994 0.99999994 0.9999997 ]
(150, 224, 224, 3)


In [4]:
#vgg model
img_data_dict_vgg={}
for i in range(10):
    img_data_dict_vgg[i]=[]
#for j in range(10):
from keras.applications.vgg16 import VGG16
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
from keras.models import Model
import numpy as np

base_model = VGG16(weights='imagenet')
model = Model(inputs=base_model.input, outputs=base_model.get_layer('fc2').output)


for j in range(10):
    img_data = np.array(img_data_dict[j])
    img_data = img_data.astype('float32')
    #print (img_data.shape)
    img_data_scaled = preprocessing.scale(img_data)
    #print (img_data_scaled.shape)
    
    #print (np.mean(img_data_scaled))
    #print (np.std(img_data_scaled))

    #print (img_data_scaled.mean(axis=0))
    #print (img_data_scaled.std(axis=0))
    img_data_scaled=img_data_scaled.reshape(img_data.shape[0],img_rows,img_cols,num_channel)
    #print (img_data_scaled.shape)
    num_of_img=img_data_scaled.shape[0]
    for k in range(num_of_img):
        img=img_data_scaled[k]
        img=np.expand_dims(img,axis=0)
        print(k)
    
    #img_path = 'elephant.jpg'
    #img = image.load_img(img_path, target_size=(224, 224))
    #x = image.img_to_array(img)
    #x = np.expand_dims(x, axis=0)
    #x = preprocess_input(x)

        features = model.predict(img)
        img_data_dict_vgg[j].append(features)
    #print(img_data_1_video.shape)
    print(j)


553467904/553467096 [==============================] - 30s 0us/step


/home/ubuntu/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/data.py:164: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "
/home/ubuntu/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/data.py:181: UserWarning: Numerical issues were encountered when scaling the data and might not be solved. The standard deviation of the data is probably very close to 0. 
  warnings.warn("Numerical issues were encountered "


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
0
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
1
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
9

86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
33

In [49]:
#key_frame and key_segment selection
#descrepiton of key_frame_segment_dict selection
#key_frame_segment_dict is a dictionary whose keys are number of videos.
#key_frame_segment_dict={num_of_videos:{num_of_clusters:[],[]-----[]}}
key_frame_segment_dict={}
for i in range(10):
        key_frame_segment_dict[i]={}
for num_of_video in range(10):
    img_data = np.array(img_data_dict_vgg[num_of_video])
    img_data = img_data.astype('float32')
    print (img_data.shape)
    img_data_scaled=img_data.reshape(img_data.shape[0],img_data.shape[2])
    print(img_data_scaled.shape)
    num_of_img=img_data_scaled[0]
    # Import the `cluster` module
    from sklearn import cluster
    from scipy.spatial.distance import euclidean
    import collections
    n_clusters=10
    # Create the KMeans model
    clf = cluster.KMeans(init='k-means++', n_clusters=10,precompute_distances=True, random_state=None)

    # Fit the training data `X_train`to the model
    k=clf.fit(img_data_scaled)
    closest_cluster=k.predict(img_data_scaled)
    cluster_centroid=k.cluster_centers_
    clustering_dict={}
    for i in range(n_clusters):
        clustering_dict[i]=[]
    i=0
    for which_cluster in closest_cluster:
        clustering_dict[which_cluster].append(img_data_dict[num_of_video][i])
        i=i+1
    clustering_dict1={}
    for i in range(n_clusters):
        clustering_dict1[i]=[]
    i=0
    for which_cluster in closest_cluster:
        clustering_dict1[which_cluster].append(img_data_scaled[i])
        i=i+1
    dicta={}
    for i in range(n_clusters):
        dicta[i]={}
    for i in range(n_clusters):
        n=np.array(clustering_dict[i]).shape[0]
        for j in range(n):
            dicta[i][euclidean(cluster_centroid[i],clustering_dict1[i][j])]=clustering_dict[i][j]
    for i in range(n_clusters):
        key_frame_segment_dict[num_of_video][i]=[]
        od = collections.OrderedDict(sorted(dicta[i].items()))
        j=0;
        for k,v in od.items():
            if(j>9):
                break
            key_frame_segment_dict[num_of_video][i].append(v)
            j=j+1  
print(np.array(key_frame_segment_dict[0][0][0]).shape)

(81, 1, 4096)
(81, 4096)
(150, 1, 4096)
(150, 4096)
(934, 1, 4096)
(934, 4096)
(150, 1, 4096)
(150, 4096)
(472, 1, 4096)
(472, 4096)
(98, 1, 4096)
(98, 4096)
(285, 1, 4096)
(285, 4096)
(344, 1, 4096)
(344, 4096)
(664, 1, 4096)
(664, 4096)
(405, 1, 4096)
(405, 4096)
(150528,)


In [117]:
#feature description
#Sconv_dict={num_of_video:{num_of_cluster:[196*512]}}
#Tconv_dict={num_of_video:{num_of_cluster:[196*512]}}
from keras.applications.vgg16 import VGG16
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
from keras.models import Model
import numpy as np

base_model = VGG16(weights='imagenet')
model = Model(inputs=base_model.input, outputs=base_model.get_layer('block5_conv3').output)

Sconv_dict={}
Tconv_dict={}
for i in range(10):
    Sconv_dict[i]={}
    Tconv_dict[i]={}
for num_of_video in range(10):
    for num_of_cluster in range(n_clusters):
        #for Sconv
        key_frame=key_frame_segment_dict[num_of_video][num_of_cluster][0]
        key_frame_scaled=key_frame.reshape(img_rows,img_cols,num_channel)
        img=np.expand_dims(key_frame_scaled,axis=0)
        Sconv_dict[num_of_video][num_of_cluster]=[]
        features = model.predict(img)
        features = np.array(features).reshape(196,512)
        Sconv_dict[num_of_video][num_of_cluster].append(features)
        #for Tconv
        C=[]
        num=np.array(key_frame_segment_dict[num_of_video][num_of_cluster]).shape[0]
        tau=8
        if(num>=tau):
            for i in range(tau):
                img=key_frame_segment_dict[num_of_video][num_of_cluster][i]
                img=key_frame.reshape(img_rows,img_cols,num_channel)
                img=np.expand_dims(key_frame_scaled,axis=0)
                features = model.predict(img)
                features = np.array(features).reshape(196,512)
                C.append(features)
        else:
            for j in range(num):
                img=key_frame_segment_dict[num_of_video][num_of_cluster][j]
                img=key_frame.reshape(img_rows,img_cols,num_channel)
                img=np.expand_dims(key_frame_scaled,axis=0)
                features = model.predict(img)
                features = np.array(features).reshape(196,512)
                C.append(features)
        mu=np.zeros((196,512))        
        if(num>=tau):
            for i in range(tau):
                mu=mu+np.array(C[i])
            mu=mu/(tau+1)
        else:
            for j in range(num):
                mu=mu+np.array(C[j])
            mu=mu/tau+1
        t=np.zeros((196,512))    
        if(num>=tau):
            for i in range(tau):
                t=t+(np.array(C[i])-mu)**2
            t=t/(tau+1)
        else:
            for j in range(num):
                  t=t+(np.array(C[j])-mu)**2
            t=t/(tau+1)
        Tconv_dict[num_of_video][num_of_cluster]=[]
        Tconv_dict[num_of_video][num_of_cluster].append(t)

(1, 196, 512)

(81, 1, 4096)

[[0. 0. 0.]
 [0. 0. 0.]]


array([[0.25, 0.5 , 0.75],
       [0.75, 1.  , 1.25]])

16